package themes

import (
	"fmt"
	"maps"
	"strings"
)

// FlattenBuiltin turns the desktop's stylesheet into the builtin.css this
// package embeds: one block per registry theme, every color token spelled
// out. On the desktop the tokens cascade (the bare :root holds Gruvbox
// Light, the three Gruvbox darks share a block, each variant overrides a
// few); flattening keeps that cascade out of the terminal. It fails when a
// registry theme is missing a token, so a desktop change cannot slip in
// half-applied. The gen command is its only caller.
func FlattenBuiltin(desktopCSS, source string) (string, error) {
	rules := parseRules(desktopCSS)
	var b strings.Builder
	fmt.Fprintf(&b, "/* Generated by internal/themes/gen from the desktop app's stylesheet.\n * Source: %s\n * Do not edit: rerun the generator when the desktop's themes change. */\n", source)
	for _, opt := range Builtin {
		want := fmt.Sprintf(`:root[data-theme="%s"]`, opt.ID)
		tokens := map[string]string{}
		matched := false
		for _, r := range rules {
			for _, sel := range r.selectors {
				if sel != ":root" && sel != want {
					continue
				}
				matched = matched || sel == want
				maps.Copy(tokens, r.tokens)
				break
			}
		}
		if !matched {
			return "", fmt.Errorf("theme %s: no %s block in the stylesheet", opt.ID, want)
		}
		fmt.Fprintf(&b, "\n%s {\n", want)
		for _, name := range TokenNames {
			c, ok := ParseColor(tokens[name])
			if !ok {
				return "", fmt.Errorf("theme %s: token %s%s is missing or not a color (%q)", opt.ID, tokenPrefix, name, tokens[name])
			}
			fmt.Fprintf(&b, "  %s%s: %d %d %d; /* %s */\n", tokenPrefix, name, c.R, c.G, c.B, c.Hex())
		}
		b.WriteString("}\n")
	}
	return b.String(), nil
}
